version: '3.7'

services:
  nats:
    image: nats
    ports:
      - "4222:4222"
    networks:
      - dev
  nginx:
    image: nginx
    volumes:
      - "./test/nginx:/usr/share/nginx/html"
    networks:
      - dev
    environment:
      - NGINX_PORT=80
  opa:
    build: ./
    # image: opa-subscribe
    volumes:
      - "./test/opa/config.yaml:/app/config.yaml"
    networks:
      - dev
    ports:
      - "8181:8181"
    command: run --server -c /app/config.yaml --log-level debug
  
networks:
  dev: